/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
module.exports = [
  {
    id: 1,
    landlord_id: 1,
    property_name: "New Westminster",
    street_address: "1115 Rupert avenue",
    city: "New Westminster",
    country: "Canada",
    description: "3BR 2BA",
    type: "Townhome",
    monthly_rent: 3500,
    rating: 4.8,
    num_reviews: 11,
    mortgage: 3700,
    strata_fee: 250,
    property_tax: 278.33,
    maintenance_fee: 600,
  },
  {
    id: 2,
    landlord_id: 1,
    property_name: "South Surrey",
    address: "28 avenue 160 St.",
    city: " South Surrey ",
    country: "Canada",
    description: "6BR 3BA",
    type: "House",
    monthly_rent: "5500",
    rating: 4.5,
    num_reviews: 8,
    mortgage: 5500,
    strata_fee: 0,
    property_tax: 375,
    maintenance_fee: 1000,
  },
  {
    id: 3,
    landlord_id: 1,
    property_name: "Vancouver",
    address: "1133 Hornby St",
    city: "Vancouver",
    country: "Canada",
    description: "1BR 1BA",
    type: "Condominium",
    monthly_rent: "2500",
    rating: 4.8,
    num_reviews: 10,
    mortgage: 3500,
    strata_fee: 300,
    property_tax: 350,
    maintenance_fee: 500,
  },
  {
    id: 4,
    landlord_id: 2,
    property_name: "Richmond",
    street_address: "789 No. 3 Road",
    city: "Richmond",
    country: "Canada",
    description: "1BR 1BA",
    type: "Loft",
    monthly_rent: 2000,
    rating: 4.6,
    num_reviews: 9,
    mortgage: 2200,
    strata_fee: 150,
    property_tax: 150,
    maintenance_fee: 300,
  },
  {
    id: 5,
    landlord_id: 2,
    property_name: "Surrey",
    street_address: "1010 King George Blvd",
    city: "Surrey",
    country: "Canada",
    description: "4BR 3BA",
    type: "House",
    monthly_rent: 4000,
    rating: 4.9,
    num_reviews: 12,
    mortgage: 4200,
    strata_fee: 0,
    property_tax: 300,
    maintenance_fee: 800,
  },
  {
    id: 6,
    landlord_id: 2,
    property_name: "Coquitlam",
    street_address: "2020 Lincoln Avenue",
    city: "Coquitlam",
    country: "Canada",
    description: "2BR 1BA",
    type: "Duplex",
    monthly_rent: 2300,
    rating: 4.4,
    num_reviews: 7,
    mortgage: 2500,
    strata_fee: 0,
    property_tax: 200,
    maintenance_fee: 450,
  },
  {
    id: 7,
    landlord_id: 3,
    property_name: "Delta",
    street_address: "1515 Boundary Bay Road",
    city: "Delta",
    country: "Canada",
    description: "2BR 2BA",
    type: "Cottage",
    monthly_rent: 2700,
    rating: 4.7,
    num_reviews: 10,
    mortgage: 2900,
    strata_fee: 0,
    property_tax: 250,
    maintenance_fee: 500,
  },
  {
    id: 8,
    landlord_id: 3,
    property_name: "Port Coquitlam",
    street_address: "1717 Shaughnessy Street",
    city: "Port Coquitlam",
    country: "Canada",
    description: "3BR 2BA",
    type: "House",
    monthly_rent: 3200,
    rating: 4.8,
    num_reviews: 11,
    mortgage: 3400,
    strata_fee: 0,
    property_tax: 280,
    maintenance_fee: 600,
  },
  {
    id: 9,
    landlord_id: 3,
    property_name: "Langley",
    street_address: "1818 Fraser Highway",
    city: "Langley",
    country: "Canada",
    description: "1BR 1BA",
    type: "Apartment",
    monthly_rent: 1800,
    rating: 4.3,
    num_reviews: 6,
    mortgage: 2000,
    strata_fee: 0,
    property_tax: 150,
    maintenance_fee: 300,
  },
  {
    id: 10,
    landlord_id: 3,
    property_name: "North Vancouver",
    street_address: "1919 Lonsdale Avenue",
    city: "North Vancouver",
    country: "Canada",
    description: "3BR 2BA",
    type: "Townhouse",
    monthly_rent: 3100,
    rating: 4.7,
    num_reviews: 9,
    mortgage: 3300,
    strata_fee: 200,
    property_tax: 270,
    maintenance_fee: 550,
  },
];
